### PR TITLE
Added Perl Implementation

### PR DESCRIPTION
**Pull request by xpucadad**
I'm trying to learn the GitHub workflow and I thought it might be interesting to add different implementations of Hello World rather than to just change the README. So I added a Perl implementation.

### CODE REVIEW

**Comment by BigAlInTheHouse** [comment]
Yea hello gm....

**Comment by BigAlInTheHouse** [comment]
cats

**Comment by BigAlInTheHouse** [comment]
Haha

**Comment by BigAlInTheHouse** [comment]
Lol

**Comment by yxuey** [comment]
wow

**Comment by DonTheorist** [comment]
lol :)  i wish i could help... but i aint got the foggy what the agenda is
on here...???

On 22 May 2014 14:08, yxuey notifications@github.com wrote:

> wow
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/octocat/Hello-World/pull/136#issuecomment-43884780.

## 

yours sincerely

Dane

**Comment by DonTheorist** [comment]
????

**Comment by sap123-zz** [comment]
lol!!

**Pull request closed without merging**
